root = "./"
testdata_dir = "testdata"
tmp_dir = ".tmp"
[build]
args_bin = []
bin = "./.tmp/main"
cmd = "go build -gcflags=\"all=-N -l\" -o .tmp/main ./cmd/api/main.go"
delay = 100
exclude_dir = [".tmp", "vendor", "docker", "legend"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv --listen=:5555 --headless=true --api-version=2 --accept-multiclient exec --continue .tmp/main"
include_dir = []
include_ext = ["go", "tpl", "tmpl"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 1000
send_interrupt = false
stop_on_error = false
[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
[log]
main_only = false
time = false
[misc]
clean_on_exit = false
[screen]
clear_on_rebuild = false
keep_scroll = true
